name: Chromatic

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: false
          exitZeroOnChanges: false

      - name: Comment PR with Chromatic link
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const buildUrl = "${{ steps.chromatic.outputs.buildUrl }}";
            const storybookUrl = "${{ steps.chromatic.outputs.storybookUrl }}";
            const prNumber = context.payload.pull_request.number;

            const body = `
              Preview disponível no [Chromatic](${buildUrl})

              Documentação interativa do Storybook: [abrir aqui](${storybookUrl})
            `;

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });
